const cookingUnits = [
    "teaspoon",
    "tablespoon",
    "cup",
    "quart",
    "ounce",
    "pound",
    "dash",
    "pinch",
    "clove",
    "kilogram",
    "gram",
    "slice",
    "piece",
    "head",
    "container",
    "bottle",
    "fillet",
    "package",
    "envelope",
    "sprig",
    "pint",
  ];
  const specificUnits = [
    "can",
    "cans",
    "ear",
    "ears",
    "large",
    "small",
    "medium",
    "lb",
    "lbs",
    "lb.",
    "lbs.",
    "bag",
    "bags",
    "tsp",
    "tsp.",
    "Tsp",
    "Tsp.",
    "Tbsp",
    "Tbsp.",
    "tbsp",
    "tbsp.",
    "oz.",
    "oz",
    "g",
    "kg",
  ];
  //Stores all the text that is to be removed
  const extraText = [
    "of",
    "to",
    "taste",
    "grated",
    "ground",
    "eaches",
    "grounded",
    "chopped",
    "sliced",
    "diced",
    "very",
    "ripe",
    "fresh",
    "freshly",
    "coarse",
    "coarsely",
    "for",
    "deep",
    "frying",
    "mince",
    "minced",
    "peeled",
    "finely",
    "crushed",
    "roughly",
    "pitted",
    "shredded",
    "uncooked",
    "cut",
    "into",
    "bite",
    "sized",
    "pieces",
    "thinly",
    "plus",
    "seeded",
    "handful",
    "a",
    "A",
    "knob",
    "thinly",
    "handful",
    "such",
    "as",
    "One",
    "deli",
    "bunch",
  ];
  const specialItems = ["skinless", "boneless", "half and half", "half-and-half", "large,"];
  const fractionTable = [
    { id: 189, value: 1 / 2 },
    { id: 188, value: 1 / 4 },
    { id: 8539, value: 1 / 8 },
    { id: 8531, value: 1 / 3 },
    { id: 190, value: 3 / 4 },
    { id: 8537, value: 1 / 6 },
    { id: 8532, value: 2 / 3 },
  ];
  const wholeFractionTable = [
    { id: "1/2", value: 1 / 2 },
    { id: "1/4", value: 1 / 4 },
    { id: "1/8", value: 1 / 8 },
    { id: "1/3", value: 1 / 3 },
    { id: "3/4", value: 3 / 4 },
    { id: "1/6", value: 1 / 6 },
    { id: "2/3", value: 2 / 3 },
  ];

  module.exports.cookingUnits = cookingUnits;
  module.exports.specificUnits = specificUnits;
  module.exports.extraText = extraText;
  module.exports.specialItems = specialItems;
  module.exports.fractionTable = fractionTable;
  module.exports.wholeFractionTable = wholeFractionTable;